# Generated by Django 4.2.9 on 2024-01-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_quiz_number_of_question_quiz_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
    ]
