# Generated by Django 4.2.9 on 2024-01-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_quiz_number_of_question_remove_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='number_of_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=1),
        ),
    ]
