# Generated by Django 4.2.9 on 2024-01-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_quiz_number_of_question_quiz_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='number_of_question',
            field=models.IntegerField(default=0),
        ),
    ]
